title: resinator
description: hello world
remote_theme: just-the-docs/just-the-docs

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  "Resinator on GitHub":
    - "//github.com/squeek502/resinator"
nav_external_links:
  - title: Resinator on GitHub
    url: https://github.com/squeek502/resinator
    hide_icon: false # set to true to hide the external link icon - defaults to false
