name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.1344+37295696e
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          arch: x86
      - uses: actions/checkout@v3
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          repository: 'squeek502/win32-samples-rc-tests'
          submodules: true
          path: 'win32-samples-rc-tests'

      - name: Install qemu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y qemu-user-static

      - run: zig version
      - run: zig env

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Test 32-bit
        if: ${{ matrix.os != 'macos-latest' }}
        run: zig build test -Dtarget=x86-native

      - name: Test big endian (mips)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: zig build test -Dtarget=mips-native -fqemu

      - name: Test big endian (powerpc64)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: zig build test -Dtarget=powerpc64-native -fqemu

      - name: Add zig-out to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        run: Add-Content $env:GITHUB_PATH "$env:GITHUB_WORKSPACE\zig-out\bin"

      - name: Setup Win32 Samples
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ./win32-samples-rc-tests
        run: .\setup.ps1

      - name: Test Win32 Samples
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ./win32-samples-rc-tests
        run: .\test.ps1 -ErrorOnAnyDiscrepancies -ErrorOnAnyLikelyPanics -IncludeWin32WillCompileErrorFiles -ExcludeLLVMRC -ExcludeWindres -ExcludeZigRC
